config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists, except: [:index] do
    resources :reviews, only: %i[new create]
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews
  has_one_attached :photo
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_bookmark, only: %i[destroy]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to '/'
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to '/'
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_bookmark_form.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-success"%>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a new bookmark</h1>

  <%= render "bookmark_form", bookmark: @bookmark  %>

  <%= link_to 'Return to your list', list_path(@list), class: 'btn btn-primary' %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="app-navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><i class="fa-solid fa-film"></i> My Watch List</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a class="navbar-brand" href="/">My Lists</a></li>
      <li>
        <a class="navbar-brand" href="lists/new">New List</a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_list_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/lists/index.html.erb
<div class="container d-flex justify-content-between" id="lists-top">
  <h1>My Lists</h1>
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Create a movie list
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <%= render "list_form", list: @list %>
        </div>
      </div>
    </div>
  </div>
  <%# <%= link_to 'Create a movie list', 'lists/new', class: "btn btn-success", local: false %>
</div>

<div class="container" id="cards">
  <% @lists.each do |list| %>
    <div class="card">
      <%= link_to list.name, "lists/#{list.id}" %>
      <% if list.photo.attached? %>
      <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container d-flex justify-content-between" id="new-lists-top">
  <h1>Create a new list</h1>
  <%= link_to "Return to all lists", '/', class: "btn btn-primary" %>
</div>

<div class="container">
  <%= render "list_form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="d-flex justify-content-center">
  <h1><%= @list.name %></h1>
</div>

<div class="container">
  <% @bookmarks = Bookmark.where(list_id: @list) %>
  <div class="cards d-flex mb-3">
    <% @bookmarks.each do |bookmark| %>
      <div class="card mx-3" style="width: 18rem;">
        <%= image_tag(bookmark.movie.poster_url, class: "card-img-top", size: '400') %>
        <%# <img class="card-img-top" src="" alt="film poster"> %>
        <div class="card-body">
          <h5><%= bookmark.movie.title %></h5>
          <p><%= bookmark.comment %></p>
        </div>
        <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    <% end %>
  </div>


  <%= link_to 'Add a movie', new_list_bookmark_path(@list), class: "btn btn-success" %>
  <%= link_to 'Delete this list', list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-warning" %>
  <%= link_to 'Return to lists', '/', class: "btn btn-primary" %>
</div>